### ISSUE TITLE
Implement `GitGutter` colors

### ISSUE THREAD

**Issue by alexventuraio** [hzchirs/vim-material#10]
Is there any way I can implement colors for the GitGutter plugin to show whenever a tracked file has changed?
Right now it looks like this and is kind of difficult to distinguish symbols:

![Screen Shot 2020-08-19 at 12 28 06](https://user-images.githubusercontent.com/13169164/90669671-9dee8080-e217-11ea-8da6-2415d4a0f77b.png)

Grouvox theme is doing something [like this here](https://github.com/morhetz/gruvbox/blob/bf2885a95efdad7bd5e4794dd0213917770d79b7/colors/gruvbox.vim#L750):
```sh
" GitGutter: {{{

hi! link GitGutterAdd GruvboxGreenSign
hi! link GitGutterChange GruvboxAquaSign
hi! link GitGutterDelete GruvboxRedSign
hi! link GitGutterChangeDelete GruvboxAquaSign

" }}}
```

**Comment by hzchirs** [comment]
Hi, thanks for your suggestion. 
I've updated a commit for GitGutter, please upgrade to the latest release and enjoy it 😄

![截圖 2020-08-21 下午9 11 41](https://user-images.githubusercontent.com/4735528/90894301-f6c64080-e3f2-11ea-8fd4-a27dcbd61fe4.png)
