### ISSUE TITLE
Theme doesn't work in standard terminal or iTerm2

### ISSUE THREAD

**Issue by Integralist** [hzchirs/vim-material#11]
I'm trying to use this theme but it's showing completely broken in _both_ macOS terminal app and even iTerm2 🤔 

At first I thought it might be something in my vim configuration, and then my bash configuration, and then even the terminal theme itself but nothing I do gets the colours to display how they're supposed to.

Example below...
<img width="961" alt="Screenshot 2020-12-15 at 14 09 48" src="https://user-images.githubusercontent.com/180050/102225513-37d0ec00-3edf-11eb-8bd4-eebbf6ec4554.png">

Any ideas what I might have configured incorrectly?

Thanks.

**Comment by Integralist** [comment]
OK so I raised this same issue with another theme I wanted to try out and turns out the issue is with the terminal theme being used (see [details here](https://www.nordtheme.com/docs/ports/vim/installation)).

> Vim in terminal mode must be used with a Nord terminal emulator theme in order to work properly! Vim in terminal mode uses the 16 color codes provided by the terminal emulator. When used with another color theme than the one provided by one of Nord's terminal emulator ports, the colors in Vim won't use Nord's color palettes! This will result in different styles than those defined by Nord Vim and could make it appear that there is a problem with the Nord Vim theme while the actual problem are missing Nord colors.

So my question is now, what terminal theme would you recommend I use (either iTerm2 or Terminal.app, preferably the latter) to get your vim theme to work correctly?

**Comment by hzchirs** [comment]
The colorscheme only for true color and gvim only. Terminal.app not supports true color. 
You could config `set termguicolors` in `.vimrc` then try again on iterm2.
