### ISSUE TITLE
W18: Invalid character in group name after lastest update

### ISSUE THREAD

**Issue by yueyejinghun** [hzchirs/vim-material#13]
Hello,

Thank you for this beautiful theme

After the last update, vim 8.2 and neovim 0.6.1 on Ubuntu 22.04 throw the following error

```
Error detected while processing /home/user/.vimrc[467]../home/user/.vim/plugged/vim-material/colors/vim-material.vim[249]..function <SNR>27_hi:
line    2:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
...
```
neovim 0.8.0 on Arch does not have this problem though
Disabling the theme eliminates the warning

Could you kindly check what caused this error?
Thanks again

**Comment by hzchirs** [comment]
Hi, I've fixed the issue.
Please upgrade to the latest.

Feel free to open the issue again if the error still remains.

**Comment by yueyejinghun** [comment]
> Hi, I've fixed the issue. Please upgrade to the latest.
> 
> Feel free to open the issue again if the error still remains.

Thanks for your efficiency.

However, it's fixed for vim 8.2, but the warning still exists on neovim 0.6.1, and I have double checked, on neovim 0.8.0 the theme works just fine.

The settings I'm using are
```
let g:airline_theme='material'
set background=dark
colorscheme vim-material
```

**Comment by hzchirs** [comment]
@yueyejinghun this issue was caused by treesitter highlight groups.
nvim version < 800 does not support group name start with '@'.

I've fixed. Please upgrade to the latest update.

**Comment by yueyejinghun** [comment]
> @yueyejinghun this issue was caused by treesitter highlight groups. nvim version < 800 does not support group name start with '@'.
> 
> I've fixed. Please upgrade to the latest update.

Of course. I don't have any more questions. Thank you very much.
