### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by tmhn** [hzchirs/vim-material#3]
Not so much an issue, more of a query: how can I change the background color when used with NVIM? Ideally I'd set it to the same colour as my iTerm config: #252625

**Comment by hzchirs** [comment]
You could override any color in your `init.vim` by putting them after the line you set colorscheme.
Here's the example for overriding the background color by `#252625`:
```vim
color vim-material
hi Normal guibg=#252625 " Override background color
```

**Comment by tmhn** [comment]
Thanks @hzchirs it worked like a dream!
