### ISSUE TITLE
about Oceanic theme

### ISSUE THREAD

**Issue by allonli** [hzchirs/vim-material#6]
Excuse me, 
Oceanic theme have a separator that continuous line in your image, Others is discontinuous dotted line, but my Oceanic theme is dotted line? And icon of dir tree have no floder picture?
![image](https://user-images.githubusercontent.com/3733955/57505276-454cea00-732a-11e9-8d88-28bc2aa4d736.png)

**Comment by hzchirs** [comment]
Hi, I found that the separator became a continuous line was after an iterm version upgrade. It seems to me that the separator's shape is base on the terminal render engine.

The folder icon is based on this plugin: https://github.com/ryanoasis/vim-devicons

**Comment by allonli** [comment]
Thanks for your reply, 
1. I fixed  continuous line problem in theme,adding a line config. I use a macvim. such as:
```
set fillchars+=vert:│
```

2. It have to add a config that line problem of have no folder icon：
```bash
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
```
