### ISSUE TITLE
Base16 theme available?

### ISSUE THREAD

**Issue by pinpox** [hzchirs/vim-material#9]
Hello, I really like your "Oceanic" theme!

Is it available as [base16](http://chriskempson.com/projects/base16/) theme?
I couldn't find it there under this name. If not, would you mind adding it there?

**Comment by hzchirs** [comment]
Thanks 😊

Before dig into base16, I wonder why you wouldn't just install the theme?

**Comment by pinpox** [comment]
Hello @hzchirs , thanks for the reply. This might not be specific to vim-material, but I use base16 for pretty much all my applications and have it setup, so that I just have to set the theme in one place and all apps (including vim) will take the changes. I  could use the theme "manually" of course, but using base16 for everything is just more "automatic"

EDIT: It's pretty easy to do, just have to create a `.yaml` file [like this](https://github.com/ntpeters/base16-materialtheme-scheme/blob/master/material.yaml) one e.g.

**Comment by hzchirs** [comment]
HI @binaryplease 
You can refer to the [palette](https://github.com/hzchirs/vim-material/blob/master/colors/vim-material.vim) (from 23 to 43) to create your own `.yaml` file for Oceanic.

**Comment by hzchirs** [comment]
Hi @binaryplease
I think you can refer to [palette](https://github.com/hzchirs/vim-material/blob/master/colors/vim-material.vim) and create your own `.yaml` file of Oceanic.
